### ISSUE TITLE
Adding contest wise solutions for popular contests.

### ISSUE THREAD

**Issue by aksh1407** [1gne0u5/Learning-Resources#17]
For contests like AtCoder DP Contest, Global Rounds of CodeForces and such contests.

**Comment by prayutsu** [comment]
@AyushiPanth @spartanss123 What are your thoughts on this?

**Comment by AyushiPanth** [comment]
Yes, this is a nice idea, we can add solutions to some good coding contests along with the problem statement link, like Kickstart, Codejam, Codeforces, AtCoder, etc.

**Comment by aksh1407** [comment]
Let's do this!
