### ISSUE TITLE
Make three subdirectories for app-dev

### ISSUE THREAD

**Issue by prayutsu** [1gne0u5/Learning-Resources#2]
Currently we have only a single main directory for app-dev, we should add two three subdirectories - native-android, native-ios and cross-platform

**Comment by tarishij17** [comment]
can you plz explain where do you want subdirectories to be added?

**Comment by prayutsu** [comment]
@tarishij17 We want sub-directories under app-dev directory

**Comment by tarishij17** [comment]
https://github.com/1gne0u5/Learning-Resources/pull/8 
plz let me know if anything else is required
