### ISSUE TITLE
Make blogs and resoucres sub-directories of each main directory

### ISSUE THREAD

**Issue by prayutsu** [1gne0u5/Learning-Resources#3]
Currently we have 'Blogs' and 'Resources' as the main directories, but we should rather have them as sub-directories in each of the main directories.

Or they should be renamed as Miscellaneous-Blogs and Miscellaneous-resources which should include the learning resources for of miscellaneous types (not relevant to just one field)

**Comment by prayutsu** [comment]
@aksh1407 @3scava1i3r  Does that make sense?

**Comment by 3scava1i3r** [comment]
blog folder should remain the same with categorization of things inside the readme and a content section for better direction towards a specific topic
